import { exec } from 'child_process';
import fs from 'fs';
import db from './db.js';

const KVM_HOSTS_CONF = process.env.NGINX_KVM_CONF ?? '/etc/nginx/kvm-hosts.conf';

interface Host {
  id: number;
  name: string;
  slug: string;
  url: string;
  order_index: number;
  max_body_size: string;
}

function buildLocationBlock(host: Host): string {
  // Ensure the URL has no trailing slash for clean concatenation
  const upstreamUrl = host.url.replace(/\/$/, '');
  return `
# ${host.name}
location ^~ /kvm/${host.slug}/ {
    proxy_pass ${upstreamUrl}/;
    proxy_ssl_verify off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    # WebRTC / streaming — disable buffering so frames flow through immediately
    proxy_buffering off;
    proxy_request_buffering off;
    proxy_cache off;
    # Per-host upload limit (for KVM image uploads)
    client_max_body_size ${host.max_body_size};
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
}`;
}

export function rewriteNginxConfig(): Promise<void> {
  const hosts = db.prepare(
    'SELECT id, name, slug, url, order_index, max_body_size FROM hosts ORDER BY order_index ASC, id ASC'
  ).all() as Host[];

  const content =
    '# Auto-generated by kvm-router API — do not edit manually\n' +
    hosts.map(buildLocationBlock).join('\n') +
    '\n';

  fs.writeFileSync(KVM_HOSTS_CONF, content, 'utf8');

  return new Promise((resolve, reject) => {
    exec('nginx -s reload', (err, _stdout, stderr) => {
      if (err) {
        // nginx may not be running in dev — log but don't crash
        console.warn('[nginx-manager] reload failed (ok in dev):', stderr || err.message);
      } else {
        console.log('[nginx-manager] nginx reloaded successfully');
      }
      resolve();
    });
  });
}
